# Generated by Django 2.2.1 on 2019-05-15 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_no', models.CharField(max_length=400)),
                ('record_no', models.CharField(max_length=400)),
                ('entry_date', models.CharField(max_length=400)),
                ('ref_no', models.CharField(max_length=400)),
                ('invoice_no', models.CharField(max_length=400)),
                ('courier_name', models.CharField(max_length=400)),
                ('con_no', models.CharField(max_length=400)),
                ('dispatch_date', models.CharField(max_length=400)),
                ('dispatch_by', models.CharField(max_length=400)),
                ('sales_date', models.CharField(max_length=400)),
                ('sales_time', models.CharField(max_length=400)),
                ('customer_name', models.CharField(max_length=400)),
                ('mail_address', models.CharField(max_length=400)),
                ('agent_name', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('zip_code', models.CharField(max_length=400)),
                ('customer_phone', models.CharField(max_length=400)),
                ('credit_card_type', models.CharField(max_length=400)),
                ('credit_card_number', models.CharField(max_length=400)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
