# Generated by Django 2.2.1 on 2019-05-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operator_form', '0002_dataentry_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='published_date',
        ),
    ]
