# Generated by Django 2.2.1 on 2019-05-17 09:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operator_form', '0004_dataentry_published_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataEntry',
            new_name='Post',
        ),
    ]
