# Generated by Django 2.2.1 on 2019-06-23 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator_form', '0005_auto_20190517_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
